[package]
name = "rust"
version = "0.1.0"
authors = ["Niraj Sapkota <n.sapkota@outlook.com.au>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = { version = "1.0", features = ["derive"] }
